version: '3'

services:
  user-service:
    build: ./UserService
    ports:
      - "8080:8080"

  email-service:
    build: ./EmailService
    ports:
      - "9090:9090"

  krakend:
    image: devopsfaith/krakend
    volumes:
      - ./krakend.json:/etc/krakend/krakend.json
    ports:
      - "8080:8080"
    depends_on:
      - user-service
      - email-service
