version: '3'

services:
  user-service:
    build:
      context: .
      dockerfile: ./user-service/Dockerfile
    ports:
      - "8080:8080"
      - "50051:50051"
      - "9101:9101"
    environment:
      - GRPC_PORT=:50051
      - HTTP_PORT=:8080
      - METRICS_PORT=:9101
      - EMAIL_SERVICE_ADDRESS=email-service:50052
      - CLIENT_EMAIL_SERVICE_TIMEOUT=5s
      - CLIENT_EMAIL_SERVICE_RETRY_ATTEMPTS=3
      - CLIENT_EMAIL_SERVICE_RETRY_DELAY=1s
      - TRACE_SERVICE_NAME=user-service
      - TRACE_JAEGER_URL=http://jaeger:14268/api/traces
      - TRACE_VERSION=1.0.0
    depends_on:
      - email-service
      - jaeger
    restart: unless-stopped

  email-service:
    build:
      context: .
      dockerfile: ./email-service/Dockerfile
    ports:
      - "50052:50052"
      - "9102:9102"
    environment:
      - GRPC_PORT=:50052
      - METRICS_PORT=:9102
      - RATE_LIMIT_RPM=60
      - RATE_LIMIT_BURST=10
      - DOWNTIME_INTERVAL=5m
      - DOWNTIME_DURATION=30s
      - DOWNTIME_ENABLED=true
      - SMTP_ENABLED=false
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USERNAME=your-email@gmail.com
      - SMTP_PASSWORD=your-app-password
      - SMTP_FROM=your-email@gmail.com
      - TRACE_SERVICE_NAME=email-service
      - TRACE_JAEGER_URL=http://jaeger:14268/api/traces
      - TRACE_VERSION=1.0.0
    depends_on:
      - jaeger
    restart: unless-stopped

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686" # UI
      - "14250:14250" # gRPC
      - "14268:14268" # HTTP collector
    environment:
      - COLLECTOR_OTLP_ENABLED=true

  krakend:
    image: devopsfaith/krakend:latest
    volumes:
      - ./krakend.json:/etc/krakend/krakend.json
    ports:
      - "8000:8000"
    depends_on:
      - user-service
      - email-service

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - user-service
      - email-service

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

networks:
  default:
    driver: bridge