global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'user-service'
    static_configs:
      - targets: ['user-service:9101']

  - job_name: 'email-service'
    static_configs:
      - targets: ['email-service:9102']