// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: api/health/health_service.proto

package health

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// HealthStatus is the status of the service.
type HealthStatus int32

const (
	HealthStatus_UNKNOWN   HealthStatus = 0
	HealthStatus_HEALTHY   HealthStatus = 1
	HealthStatus_UNHEALTHY HealthStatus = 2
	HealthStatus_ALIVE     HealthStatus = 3
	HealthStatus_READY     HealthStatus = 4
)

// Enum value maps for HealthStatus.
var (
	HealthStatus_name = map[int32]string{
		0: "UNKNOWN",
		1: "HEALTHY",
		2: "UNHEALTHY",
		3: "ALIVE",
		4: "READY",
	}
	HealthStatus_value = map[string]int32{
		"UNKNOWN":   0,
		"HEALTHY":   1,
		"UNHEALTHY": 2,
		"ALIVE":     3,
		"READY":     4,
	}
)

func (x HealthStatus) Enum() *HealthStatus {
	p := new(HealthStatus)
	*p = x
	return p
}

func (x HealthStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HealthStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_health_health_service_proto_enumTypes[0].Descriptor()
}

func (HealthStatus) Type() protoreflect.EnumType {
	return &file_api_health_health_service_proto_enumTypes[0]
}

func (x HealthStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HealthStatus.Descriptor instead.
func (HealthStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_health_health_service_proto_rawDescGZIP(), []int{0}
}

// HealthCheckRequest is the request message for health check RPCs.
type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_api_health_health_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_health_health_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_api_health_health_service_proto_rawDescGZIP(), []int{0}
}

// HealthCheckResponse is the response message for health check RPCs.
type HealthCheckResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// status is the health status of the service.
	Status        HealthStatus `protobuf:"varint,1,opt,name=status,proto3,enum=health.HealthStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_api_health_health_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_health_health_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_api_health_health_service_proto_rawDescGZIP(), []int{1}
}

func (x *HealthCheckResponse) GetStatus() HealthStatus {
	if x != nil {
		return x.Status
	}
	return HealthStatus_UNKNOWN
}

var File_api_health_health_service_proto protoreflect.FileDescriptor

const file_api_health_health_service_proto_rawDesc = "" +
	"\n" +
	"\x1fapi/health/health_service.proto\x12\x06health\x1a\x1cgoogle/api/annotations.proto\"\x14\n" +
	"\x12HealthCheckRequest\"C\n" +
	"\x13HealthCheckResponse\x12,\n" +
	"\x06status\x18\x01 \x01(\x0e2\x14.health.HealthStatusR\x06status*M\n" +
	"\fHealthStatus\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\v\n" +
	"\aHEALTHY\x10\x01\x12\r\n" +
	"\tUNHEALTHY\x10\x02\x12\t\n" +
	"\x05ALIVE\x10\x03\x12\t\n" +
	"\x05READY\x10\x042\xf6\x02\n" +
	"\rHealthService\x12T\n" +
	"\x05Check\x12\x1a.health.HealthCheckRequest\x1a\x1b.health.HealthCheckResponse\"\x12\x82\xd3\xe4\x93\x02\f\x12\n" +
	"/v1/health\x12Y\n" +
	"\bLiveness\x12\x1a.health.HealthCheckRequest\x1a\x1b.health.HealthCheckResponse\"\x14\x82\xd3\xe4\x93\x02\x0e\x12\f/v1/liveness\x12[\n" +
	"\tReadiness\x12\x1a.health.HealthCheckRequest\x1a\x1b.health.HealthCheckResponse\"\x15\x82\xd3\xe4\x93\x02\x0f\x12\r/v1/readiness\x12W\n" +
	"\aHealthz\x12\x1a.health.HealthCheckRequest\x1a\x1b.health.HealthCheckResponse\"\x13\x82\xd3\xe4\x93\x02\r\x12\v/v1/healthzBAZ?github.com/popeskul/mailflow/user-service/pkg/api/health;healthb\x06proto3"

var (
	file_api_health_health_service_proto_rawDescOnce sync.Once
	file_api_health_health_service_proto_rawDescData []byte
)

func file_api_health_health_service_proto_rawDescGZIP() []byte {
	file_api_health_health_service_proto_rawDescOnce.Do(func() {
		file_api_health_health_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_health_health_service_proto_rawDesc), len(file_api_health_health_service_proto_rawDesc)))
	})
	return file_api_health_health_service_proto_rawDescData
}

var file_api_health_health_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_health_health_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_health_health_service_proto_goTypes = []any{
	(HealthStatus)(0),           // 0: health.HealthStatus
	(*HealthCheckRequest)(nil),  // 1: health.HealthCheckRequest
	(*HealthCheckResponse)(nil), // 2: health.HealthCheckResponse
}
var file_api_health_health_service_proto_depIdxs = []int32{
	0, // 0: health.HealthCheckResponse.status:type_name -> health.HealthStatus
	1, // 1: health.HealthService.Check:input_type -> health.HealthCheckRequest
	1, // 2: health.HealthService.Liveness:input_type -> health.HealthCheckRequest
	1, // 3: health.HealthService.Readiness:input_type -> health.HealthCheckRequest
	1, // 4: health.HealthService.Healthz:input_type -> health.HealthCheckRequest
	2, // 5: health.HealthService.Check:output_type -> health.HealthCheckResponse
	2, // 6: health.HealthService.Liveness:output_type -> health.HealthCheckResponse
	2, // 7: health.HealthService.Readiness:output_type -> health.HealthCheckResponse
	2, // 8: health.HealthService.Healthz:output_type -> health.HealthCheckResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_health_health_service_proto_init() }
func file_api_health_health_service_proto_init() {
	if File_api_health_health_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_health_health_service_proto_rawDesc), len(file_api_health_health_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_health_health_service_proto_goTypes,
		DependencyIndexes: file_api_health_health_service_proto_depIdxs,
		EnumInfos:         file_api_health_health_service_proto_enumTypes,
		MessageInfos:      file_api_health_health_service_proto_msgTypes,
	}.Build()
	File_api_health_health_service_proto = out.File
	file_api_health_health_service_proto_goTypes = nil
	file_api_health_health_service_proto_depIdxs = nil
}
