// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: api/email/v1/email_service.proto

package emailv1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Email struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	To            string                 `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	Subject       string                 `protobuf:"bytes,3,opt,name=subject,proto3" json:"subject,omitempty"`
	Body          string                 `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	SentAt        string                 `protobuf:"bytes,7,opt,name=sent_at,json=sentAt,proto3" json:"sent_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Email) Reset() {
	*x = Email{}
	mi := &file_api_email_v1_email_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Email) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Email) ProtoMessage() {}

func (x *Email) ProtoReflect() protoreflect.Message {
	mi := &file_api_email_v1_email_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Email.ProtoReflect.Descriptor instead.
func (*Email) Descriptor() ([]byte, []int) {
	return file_api_email_v1_email_service_proto_rawDescGZIP(), []int{0}
}

func (x *Email) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Email) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *Email) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *Email) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *Email) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Email) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Email) GetSentAt() string {
	if x != nil {
		return x.SentAt
	}
	return ""
}

type SendEmailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	To            string                 `protobuf:"bytes,1,opt,name=to,proto3" json:"to,omitempty"`
	Subject       string                 `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	Body          string                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendEmailRequest) Reset() {
	*x = SendEmailRequest{}
	mi := &file_api_email_v1_email_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendEmailRequest) ProtoMessage() {}

func (x *SendEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_email_v1_email_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendEmailRequest.ProtoReflect.Descriptor instead.
func (*SendEmailRequest) Descriptor() ([]byte, []int) {
	return file_api_email_v1_email_service_proto_rawDescGZIP(), []int{1}
}

func (x *SendEmailRequest) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *SendEmailRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *SendEmailRequest) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

type SendEmailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendEmailResponse) Reset() {
	*x = SendEmailResponse{}
	mi := &file_api_email_v1_email_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendEmailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendEmailResponse) ProtoMessage() {}

func (x *SendEmailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_email_v1_email_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendEmailResponse.ProtoReflect.Descriptor instead.
func (*SendEmailResponse) Descriptor() ([]byte, []int) {
	return file_api_email_v1_email_service_proto_rawDescGZIP(), []int{2}
}

func (x *SendEmailResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SendEmailResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GetEmailStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEmailStatusRequest) Reset() {
	*x = GetEmailStatusRequest{}
	mi := &file_api_email_v1_email_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEmailStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEmailStatusRequest) ProtoMessage() {}

func (x *GetEmailStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_email_v1_email_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEmailStatusRequest.ProtoReflect.Descriptor instead.
func (*GetEmailStatusRequest) Descriptor() ([]byte, []int) {
	return file_api_email_v1_email_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetEmailStatusRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetEmailStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	SentAt        string                 `protobuf:"bytes,3,opt,name=sent_at,json=sentAt,proto3" json:"sent_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEmailStatusResponse) Reset() {
	*x = GetEmailStatusResponse{}
	mi := &file_api_email_v1_email_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEmailStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEmailStatusResponse) ProtoMessage() {}

func (x *GetEmailStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_email_v1_email_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEmailStatusResponse.ProtoReflect.Descriptor instead.
func (*GetEmailStatusResponse) Descriptor() ([]byte, []int) {
	return file_api_email_v1_email_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetEmailStatusResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetEmailStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetEmailStatusResponse) GetSentAt() string {
	if x != nil {
		return x.SentAt
	}
	return ""
}

type ListEmailsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      int32                  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEmailsRequest) Reset() {
	*x = ListEmailsRequest{}
	mi := &file_api_email_v1_email_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEmailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEmailsRequest) ProtoMessage() {}

func (x *ListEmailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_email_v1_email_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEmailsRequest.ProtoReflect.Descriptor instead.
func (*ListEmailsRequest) Descriptor() ([]byte, []int) {
	return file_api_email_v1_email_service_proto_rawDescGZIP(), []int{5}
}

func (x *ListEmailsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListEmailsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListEmailsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Emails        []*Email               `protobuf:"bytes,1,rep,name=emails,proto3" json:"emails,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEmailsResponse) Reset() {
	*x = ListEmailsResponse{}
	mi := &file_api_email_v1_email_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEmailsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEmailsResponse) ProtoMessage() {}

func (x *ListEmailsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_email_v1_email_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEmailsResponse.ProtoReflect.Descriptor instead.
func (*ListEmailsResponse) Descriptor() ([]byte, []int) {
	return file_api_email_v1_email_service_proto_rawDescGZIP(), []int{6}
}

func (x *ListEmailsResponse) GetEmails() []*Email {
	if x != nil {
		return x.Emails
	}
	return nil
}

func (x *ListEmailsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

var File_api_email_v1_email_service_proto protoreflect.FileDescriptor

const file_api_email_v1_email_service_proto_rawDesc = "" +
	"\n" +
	" api/email/v1/email_service.proto\x12\bemail.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"\xb4\x01\n" +
	"\x05Email\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x13\n" +
	"\x02to\x18\x02 \x01(\tB\x03\xe0A\x02R\x02to\x12\x1d\n" +
	"\asubject\x18\x03 \x01(\tB\x03\xe0A\x02R\asubject\x12\x17\n" +
	"\x04body\x18\x04 \x01(\tB\x03\xe0A\x02R\x04body\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\x12\x17\n" +
	"\asent_at\x18\a \x01(\tR\x06sentAt\"_\n" +
	"\x10SendEmailRequest\x12\x13\n" +
	"\x02to\x18\x01 \x01(\tB\x03\xe0A\x02R\x02to\x12\x1d\n" +
	"\asubject\x18\x02 \x01(\tB\x03\xe0A\x02R\asubject\x12\x17\n" +
	"\x04body\x18\x03 \x01(\tB\x03\xe0A\x02R\x04body\";\n" +
	"\x11SendEmailResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\",\n" +
	"\x15GetEmailStatusRequest\x12\x13\n" +
	"\x02id\x18\x01 \x01(\tB\x03\xe0A\x02R\x02id\"Y\n" +
	"\x16GetEmailStatusResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x17\n" +
	"\asent_at\x18\x03 \x01(\tR\x06sentAt\"O\n" +
	"\x11ListEmailsRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\"e\n" +
	"\x12ListEmailsResponse\x12'\n" +
	"\x06emails\x18\x01 \x03(\v2\x0f.email.v1.EmailR\x06emails\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken2\xcb\x02\n" +
	"\fEmailService\x12c\n" +
	"\tSendEmail\x12\x1a.email.v1.SendEmailRequest\x1a\x1b.email.v1.SendEmailResponse\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/api/v1/email/send\x12v\n" +
	"\x0eGetEmailStatus\x12\x1f.email.v1.GetEmailStatusRequest\x1a .email.v1.GetEmailStatusResponse\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/api/v1/email/{id}/status\x12^\n" +
	"\n" +
	"ListEmails\x12\x1b.email.v1.ListEmailsRequest\x1a\x1c.email.v1.ListEmailsResponse\"\x15\x82\xd3\xe4\x93\x02\x0f\x12\r/api/v1/emailBEZCgithub.com/popeskul/mailflow/email-service/pkg/api/email/v1;emailv1b\x06proto3"

var (
	file_api_email_v1_email_service_proto_rawDescOnce sync.Once
	file_api_email_v1_email_service_proto_rawDescData []byte
)

func file_api_email_v1_email_service_proto_rawDescGZIP() []byte {
	file_api_email_v1_email_service_proto_rawDescOnce.Do(func() {
		file_api_email_v1_email_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_email_v1_email_service_proto_rawDesc), len(file_api_email_v1_email_service_proto_rawDesc)))
	})
	return file_api_email_v1_email_service_proto_rawDescData
}

var file_api_email_v1_email_service_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_api_email_v1_email_service_proto_goTypes = []any{
	(*Email)(nil),                  // 0: email.v1.Email
	(*SendEmailRequest)(nil),       // 1: email.v1.SendEmailRequest
	(*SendEmailResponse)(nil),      // 2: email.v1.SendEmailResponse
	(*GetEmailStatusRequest)(nil),  // 3: email.v1.GetEmailStatusRequest
	(*GetEmailStatusResponse)(nil), // 4: email.v1.GetEmailStatusResponse
	(*ListEmailsRequest)(nil),      // 5: email.v1.ListEmailsRequest
	(*ListEmailsResponse)(nil),     // 6: email.v1.ListEmailsResponse
}
var file_api_email_v1_email_service_proto_depIdxs = []int32{
	0, // 0: email.v1.ListEmailsResponse.emails:type_name -> email.v1.Email
	1, // 1: email.v1.EmailService.SendEmail:input_type -> email.v1.SendEmailRequest
	3, // 2: email.v1.EmailService.GetEmailStatus:input_type -> email.v1.GetEmailStatusRequest
	5, // 3: email.v1.EmailService.ListEmails:input_type -> email.v1.ListEmailsRequest
	2, // 4: email.v1.EmailService.SendEmail:output_type -> email.v1.SendEmailResponse
	4, // 5: email.v1.EmailService.GetEmailStatus:output_type -> email.v1.GetEmailStatusResponse
	6, // 6: email.v1.EmailService.ListEmails:output_type -> email.v1.ListEmailsResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_email_v1_email_service_proto_init() }
func file_api_email_v1_email_service_proto_init() {
	if File_api_email_v1_email_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_email_v1_email_service_proto_rawDesc), len(file_api_email_v1_email_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_email_v1_email_service_proto_goTypes,
		DependencyIndexes: file_api_email_v1_email_service_proto_depIdxs,
		MessageInfos:      file_api_email_v1_email_service_proto_msgTypes,
	}.Build()
	File_api_email_v1_email_service_proto = out.File
	file_api_email_v1_email_service_proto_goTypes = nil
	file_api_email_v1_email_service_proto_depIdxs = nil
}
